### ISSUE TITLE
You may need an appropriate loader to handle this file type.

### ISSUE THREAD

**Issue by freya0608** [justQing00/react-watermark#1]
`Module parse failed: /Users/freya/_git/Sparta-Webapp/node_modules/react-watermark/components/watermark.jsx Unexpected token (96:17)
You may need an appropriate loader to handle this file type.
|         minHeight: wm_height + 'px',
|       };
|       marks.push(<SingleMark key={`${i}-${j}`} style={style}>{wm_txt}</SingleMark>);
|     };
|   };
`

**Comment by justQing00** [comment]
you need to make webpack support jsx file, like set compile file type.
